---
author: Dan Kelley
title: Julia/vim setup
---

# How to use this setup

Suppose you want to edit a file (`a.jl` say) in neovim and run Julia at the
same time.

1. Start a `tmux` session (if not already started).

2. Type `J a.jl` to split the tmux window vertically, launching neovim editing
   `a.jl` in the top window and running Julia in the bottom window.

3. In the neovim window, type C-c C-c to run the code in the paragraph (i.e.
   a block of code ended with either a blank line or the end of the file)
   containing the cursor.  The first time you do this in a session, it will ask
   you two questions; type ENTER for each.  Once you've done that, you will see
   the result of running your `a.jl` code appear in the julia window (and maybe
   in plotting windows, if you have any).

4. Move from paragraph to paragraph, running each.  Or, just don't use
   paragraphs.

# How to ... um... set up this setup

1. Edit your `~/.zshrc` file (if you use the Z shell, or `~/.bashrc` if you use
   bash, etc), adding the following.  (I got this from
   https://proceed-to-decode.com/posts/vim-tmux-julia but the instructions
   there assumed you were not already in tmux.)

```
function J() {
    tmux  send-keys "vim $1" Enter \; \
        split-window -v \; \
        rename-window julia \; \
        send-keys "julia" Enter \; \
        select-pane -t 0 \;
        }
```

2. Edit your `~/.vimrc` file, adding the following to your Plug setup.  I got
   much of this from https://www.youtube.com/watch?v=GazrDjcdeG4 at 15:52,
   although there are lots of other sources dealing with this sort of thing.
   The remapping of <Space>j is something I made up, corresponding to <Space>r
   in R mode.
```
" Slime
let g:slime_target = "tmux"
let g:slime_default_config = {"socket_name": "default", "target_pane": "{last}"}
let g:slime_dont_ask_default = 1
" Julia: make <Space>j run current line. Note that <C-c><C-c> runs paragraph.
autocmd Filetype julia xnoremap <Space>j :SlimeSendCurrentLine<cr>
autocmd Filetype julia nnoremap <Space>j :SlimeSendCurrentLine<cr>
```


# Further steps

I might add an alias to run just a single line of code.

