thumbnails: pisa-scores-thumbnail.png webtide1-thumbnail.png webtide2-thumbnail.png \
    colorline-thumbnail.png webtideosx1-thumbnail.png webtideosx2-thumbnail.png \
    sundial_with_gnomon-thumbnail.png analemma-thumbnail.png \
    coastline-switch-1-thumbnail.png coastline-switch-2-thumbnail.png \
    vote-split-thumbnail.png smooth-profile-thumbnail.png \
    solstice_sunrise_sunset-thumbnail.png

pisa-scores-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 pisa-scores.png pisa-scores-thumbnail.png;
webtide1-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 webtide1.png webtide-thumbnail1.png;
webtide2-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 webtide2.png webtide-thumbnail2.png;
webtideosx1-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 webtideosx1.png webtideosx1-thumbnail.png;
webtideosx2-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 webtideosx2.png webtideosx2-thumbnail.png;
colorline-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 colorline.png colorline-thumbnail.png;
sundial_with_gnomon-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 sundial_with_gnomon.png sundial_with_gnomon-thumbnail.png;
analemma-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 analemma.png analemma-thumbnail.png;
coastline-switch-1-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 coastline-switch-1.png coastline-switch-1-thumbnail.png;
coastline-switch-2-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 coastline-switch-2.png coastline-switch-2-thumbnail.png;
vote-split-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 vote-split.png vote-split-thumbnail.png;
smooth-profile-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 smooth-profile.png smooth-profile-thumbnail.png;
solstice_sunrise_sunset-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 solstice_sunrise_sunset.png solstice_sunrise_sunset-thumbnail.png;

force:

