thumbnails: pisa-scores-thumbnail.png webtide1-thumbnail.png webtide2-thumbnail.png colorline-thumbnail.png webtideosx1-thumbnail.png webtideosx2-thumbnail.png


pisa-scores-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 pisa-scores.png pisa-scores-thumbnail.png;
webtide1-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 webtide1.png webtide-thumbnail1.png;
webtide2-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 webtide2.png webtide-thumbnail2.png;
webtideosx1-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 webtideosx1.png webtideosx1-thumbnail.png;
webtideosx2-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 webtideosx2.png webtideosx2-thumbnail.png;
colorline-thumbnail.png: force
	/usr/local/bin/convert -thumbnail 400x400 colorline.png colorline-thumbnail.png;

force:

